/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Sales;

import BUS.Employee.EmployeeBUS;
import Bus.BillBUS;
import Bus.CthdBUS;
import Bus.CustomerBUS;
import Bus.ProductBUS;
import Bus.PromotionBUS;
import Bus.StaffBUS;
import Inventory.DAO.ProductDAO;
import Inventory.DTO.BillDTO;
import Inventory.DTO.CthdDTO;
import Inventory.DTO.CustomerDTO;
import Inventory.DTO.ProductDTO;
import Inventory.DTO.PromotionDTO;
import Inventory.DTO.StaffDTO;
import UI.HomePage;
import java.text.DecimalFormat;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.*;
import javax.swing.table.*;

/**
 *
 * @author Admin
 */
public class SalesPage extends javax.swing.JPanel {

    HomePage homepage;
    int soLuongCTHD = 0;
    int cthdCreated = 0;
    int oldSPId = -1;
    int selectedRow = -1;
    DefaultTableModel model1;
    CthdBUS bus = new CthdBUS();
    ProductBUS bus1 = new ProductBUS();
    BillBUS bus2 = new BillBUS();
    EmployeeBUS bus3 = new EmployeeBUS();
    StaffDTO staff = new StaffDTO();
    PromotionBUS bus4 = new PromotionBUS();
    CustomerBUS bus5 = new CustomerBUS();
    int tongHoaDon = 0;
    double tongTien;

    /**
     * Creates new form SalesPage
     */
    public SalesPage(HomePage homepage) {
        initComponents();
        this.homepage = homepage;
        loadBill("something");
        // tải dữ liệu nè
        addSPValues();
        addKHValues();
        addKMValues();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tgLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        kMLabel = new javax.swing.JLabel();
        idNVLabel = new javax.swing.JLabel();
        tongLabel = new javax.swing.JLabel();
        idKHLabel = new javax.swing.JLabel();
        tongHoaDonLabel = new javax.swing.JLabel();
        xuatHDBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTHD = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        giaTienLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tenSPLabel = new javax.swing.JLabel();
        soLuongField = new javax.swing.JTextField();
        thanhTienLabel = new javax.swing.JLabel();
        tenSPField = new javax.swing.JTextField();
        giaTienField = new javax.swing.JTextField();
        thanhTienField = new javax.swing.JTextField();
        demCTHD1 = new javax.swing.JLabel();
        idSPCB = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        createBillBtn = new javax.swing.JButton();
        idNVField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        idHDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        demCTHD = new javax.swing.JLabel();
        idKHCB = new javax.swing.JComboBox<>();
        idKMCB = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1126, 710));
        setMinimumSize(new java.awt.Dimension(1125, 710));
        setPreferredSize(new java.awt.Dimension(1125, 710));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID Khách hàng :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Thêm CTHD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tgLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tgLabel.setText("Thời gian :");

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idLabel.setText("Id hóa đơn :");

        kMLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kMLabel.setText("KM / Giảm giá :");

        idNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idNVLabel.setText("Id nhân viên :");

        tongLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tongLabel.setText("Tổng cộng :");

        idKHLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idKHLabel.setText("Id khách hàng :");

        tongHoaDonLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tongHoaDonLabel.setText("Phải thanh toán :");

        xuatHDBtn.setText("Xuất hóa đơn");
        xuatHDBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xuatHDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatHDBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hóa đơn");

        tableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCTHD);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(idNVLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idKHLabel)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tongLabel)
                            .addComponent(idLabel)
                            .addComponent(tgLabel)
                            .addComponent(kMLabel)
                            .addComponent(tongHoaDonLabel))
                        .addGap(0, 231, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(xuatHDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(tgLabel)
                .addGap(12, 12, 12)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idKHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tongLabel)
                .addGap(18, 18, 18)
                .addComponent(kMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tongHoaDonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xuatHDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("ID nhân viên :");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 123));

        giaTienLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaTienLabel.setText("Giá tiền :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Id sản phẩm :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Số lượng :");

        tenSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenSPLabel.setText("Tên sản phẩm :");

        soLuongField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soLuongField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                soLuongFieldFocusLost(evt);
            }
        });

        thanhTienLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thanhTienLabel.setText("Thành tiền :");

        tenSPField.setBackground(new java.awt.Color(242, 242, 242));
        tenSPField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tenSPField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tenSPField.setEnabled(false);

        giaTienField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giaTienField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        giaTienField.setEnabled(false);

        thanhTienField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thanhTienField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        thanhTienField.setEnabled(false);

        demCTHD1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        demCTHD1.setText("Chi tiết hóa đơn :");

        idSPCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idSPCB.setMaximumRowCount(8);
        idSPCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        idSPCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idSPCB.setPreferredSize(new java.awt.Dimension(72, 30));
        idSPCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idSPCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giaTienLabel)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenSPLabel)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(giaTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(thanhTienLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(thanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tenSPField, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(idSPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(soLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(68, 68, 68))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(demCTHD1)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(demCTHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(soLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idSPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenSPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaTienLabel)
                    .addComponent(giaTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thanhTienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thanh toán");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBtn.setText("Xóa");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        confirmBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmBtn.setText("Xác nhận");
        confirmBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        createBillBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createBillBtn.setText("Tạo mới");
        createBillBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBillBtnActionPerformed(evt);
            }
        });

        idNVField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idNVField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idNVField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("ID hóa đơn :");

        idHDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idHDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idHDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idHDFieldFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID Khuyến mãi :");

        demCTHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        demCTHD.setText("Thông tin hóa đơn :");

        idKHCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idKHCB.setMaximumRowCount(8);
        idKHCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        idKHCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idKHCB.setPreferredSize(new java.awt.Dimension(72, 30));
        idKHCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idKHCBItemStateChanged(evt);
            }
        });

        idKMCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idKMCB.setMaximumRowCount(5);
        idKMCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        idKMCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idKMCB.setMinimumSize(new java.awt.Dimension(72, 30));
        idKMCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idKMCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(demCTHD))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(idNVField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idHDField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idKHCB, 0, 97, Short.MAX_VALUE)
                                .addComponent(idKMCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)))))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(demCTHD)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idHDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(idKHCB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idNVField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(idKMCB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearText();
        selectedRow = -1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(idSPCB.getSelectedItem()).equals("") | soLuongField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ thông tin !");
        } else {
            if (selectedRow != -1 && oldSPId != -1) {
                // chỉnh sửa
                String idHD = idHDField.getText();
                String idSP = (String) idSPCB.getSelectedItem();
                String soLuong = soLuongField.getText();
                String giaTien = giaTienField.getText();
                String tenSP = tenSPField.getText();
                CthdDTO cthd = new CthdDTO(Integer.parseInt(idHD), idSP, tenSP, Integer.parseInt(soLuong), Double.parseDouble(giaTien), 1);
                bus.updateCTHD(cthd, String.valueOf(oldSPId));
                loadBill(idHD);
                oldSPId = -1;
                clearText();
            } else { // thêm cthd
                addProduct();
                clearText();
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (selectedRow != -1) {
            String removeId = (String) idSPCB.getSelectedItem();
            int idHD = Integer.parseInt(idHDField.getText());
            bus.removeCTHD(removeId, idHD);
            loadBill(String.valueOf(idHD));
            clearText();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void soLuongFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_soLuongFieldFocusLost
        // TODO add your handling code here:
        // kiểm tra số lượng lớn hơn 0 và là số nguyên sau đó trả về dữ liệu cho giá tiền thành tiền ( nếu textField khác null)
        if (!soLuongField.getText().equals("") && !String.valueOf(idSPCB.getSelectedItem()).equals("0")) {
            if (soLuongField.getText().matches("\\d+") && Integer.parseInt(soLuongField.getText()) > 0 && Integer.parseInt(soLuongField.getText()) == Math.floor(Integer.parseInt(soLuongField.getText()))) {
                if (bus1.checkQuantity(tenSPField.getText(), Integer.parseInt(soLuongField.getText()))) {
                    ArrayList<ProductDTO> productlist = bus1.searchProductById(String.valueOf(idSPCB.getSelectedItem()));
                    ProductDTO product = new ProductDTO();
                    product = productlist.get(0);
                    double tong = product.getGia() * Integer.parseInt(soLuongField.getText());
                    giaTienField.setText(String.valueOf(product.getGia()));
                    thanhTienField.setText(String.valueOf(tong));
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng sản phẩm còn lại không đủ !");
                    soLuongField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hãy nhập đúng số lượng !");
                soLuongField.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hãy điền id sản phẩm !");
            soLuongField.setText("");
        }
    }//GEN-LAST:event_soLuongFieldFocusLost

    private void tableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTHDMouseClicked
        // TODO add your handling code here:
        selectedRow = tableCTHD.getSelectedRow();
        if (selectedRow != -1) {
            tenSPField.setText(tableCTHD.getValueAt(selectedRow, 0).toString());
            soLuongField.setText(tableCTHD.getValueAt(selectedRow, 1).toString());
            giaTienField.setText(tableCTHD.getValueAt(selectedRow, 2).toString());
            thanhTienField.setText(tableCTHD.getValueAt(selectedRow, 3).toString());
            //  
            ArrayList<ProductDTO> productlist = bus1.searchProductByName(tableCTHD.getValueAt(selectedRow, 0).toString());
//            idSanPhamField.setText(productlist.get(0).getId());
            idSPCB.setSelectedItem((String) productlist.get(0).getId());
            oldSPId = Integer.parseInt(String.valueOf(idSPCB.getSelectedItem()));
        }
    }//GEN-LAST:event_tableCTHDMouseClicked

    private void xuatHDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatHDBtnActionPerformed
        // TODO add your handling code here:
        // Xuất hóa đơn cho khách hàng
        int rowNumber = tableCTHD.getRowCount();
        if (rowNumber == -1 || idNVField.getText().equals("") || String.valueOf(idKHCB.getSelectedItem()).equals("") || idHDField.getText().equals("") || String.valueOf(idKMCB.getSelectedItem()).equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ thông tin !");
        } else {
            // Lưu hóa đơn vào DB ( CTHD đã được lưu rồi kh cần thao tác nữa )
            java.util.Date utilDate = new java.util.Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yy/MM/dd");
            String formattedDate = sdf.format(utilDate);
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            BillDTO newbill = new BillDTO(Integer.parseInt(idHDField.getText()), idNVField.getText(), String.valueOf(idKHCB.getSelectedItem()), rowNumber, String.valueOf(idKMCB.getSelectedItem()), tongTien, sqlDate, 1);
            ArrayList<BillDTO> bills = bus2.getAllBills();
            // nhập mới và chỉnh sửa
            if (!bus2.checkAvaiable(newbill.getId())) {
                bus2.addBill(newbill);
                // Cập nhật số lượng hàng hóa
                for (int i = 0; i < rowNumber; i++) {
                    String idSP = tableCTHD.getValueAt(i, 0).toString();
                    int soLuong = Integer.parseInt(tableCTHD.getValueAt(i, 1).toString());
                    bus1.decreaseProductQuantity(idSP, soLuong);
                }
            } else {
                bus2.updateBill(newbill);
            }
            JOptionPane.showMessageDialog(null, "Xuất hóa đơn thành công !");
            createNewBill();
            loadBill("something");
            clearText();

        }
    }//GEN-LAST:event_xuatHDBtnActionPerformed

    private void createBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBillBtnActionPerformed
        // TODO add your handling code here:
        // tạo 1 hóa đơn mới, show id hóa đơn mới
        createNewBill();
    }//GEN-LAST:event_createBillBtnActionPerformed

    private void idHDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idHDFieldFocusLost
        // TODO add your handling code here:
        if (!idHDField.getText().equals("")) {
            if (bus2.checkAvaiable(Integer.parseInt(idHDField.getText()))) {
                JOptionPane.showMessageDialog(null, "Id hóa đơn đã tồn tại !");
                idHDField.setText("");
            } else {
                idLabel.setText("Id hóa đơn : " + idHDField.getText());
            }
        }
    }//GEN-LAST:event_idHDFieldFocusLost

    private void idSPCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idSPCBItemStateChanged
        // TODO add your handling code here:=
        if (!String.valueOf(idSPCB.getSelectedItem()).equals("0")) {
            ArrayList<ProductDTO> productlist = bus1.searchProductById(String.valueOf(idSPCB.getSelectedItem()));
            ProductDTO product = new ProductDTO();
            product = productlist.get(0);
            tenSPField.setText(product.getTen());
        } else {
            tenSPField.setText("");
        }
    }//GEN-LAST:event_idSPCBItemStateChanged

    private void idKHCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idKHCBItemStateChanged
        // TODO add your handling code here:
        if (!String.valueOf(idKHCB.getSelectedItem()).equals("0")) {
            idKHLabel.setText("Id khách hàng : " + String.valueOf(idKHCB.getSelectedItem()));
        }
    }//GEN-LAST:event_idKHCBItemStateChanged

    private void idKMCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idKMCBItemStateChanged
        // TODO add your handling code here:
        if (!String.valueOf(idKMCB.getSelectedItem()).equals("0")) {
            ArrayList<PromotionDTO> pro = bus4.searchPromotionById(String.valueOf(idKMCB.getSelectedItem()));
            kMLabel.setText("KM / Giảm giá : " + pro.get(0).getPhanTramGiamGia() + "%");
            loadBill(idHDField.getText());
        } else {
            kMLabel.setText("KM / Giảm giá :");
        }
    }//GEN-LAST:event_idKMCBItemStateChanged

    void addKHValues() {
        ArrayList<CustomerDTO> customers = bus5.getAllCustomers();
        for (CustomerDTO cus : customers) {
            idKHCB.addItem(String.valueOf(cus.getId()));
        }
    }

    void addKMValues() {
        ArrayList<PromotionDTO> promotions = bus4.getAllPromotions();
        for (PromotionDTO pro : promotions) {
            idKMCB.addItem(String.valueOf(pro.getId()));
        }
    }

    void addSPValues() {
        ArrayList<ProductDTO> products = bus1.getAllProducts();
        for (ProductDTO prod : products) {
            idSPCB.addItem(prod.getId());
        }
    }

    void createNewBill() {
        idHDField.setEnabled(true);
        idHDField.setText("");
        idLabel.setText("Id hóa đơn : ");
        idNVField.setText(String.valueOf(homepage.staff.getStaID()));
        idNVLabel.setText("Id nhân viên : " + String.valueOf(homepage.staff.getStaID()));
        idKHLabel.setText("Id khách hàng : ");
        tongLabel.setText("Tổng cộng : ");
        kMLabel.setText("KM / Giảm giá :");
        tongHoaDonLabel.setText("Phải thanh toán : ");
        loadBill("something");
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        String formattedDate = sdf.format(date);
        tgLabel.setText("Thời gian : " + formattedDate);
        idSPCB.setSelectedItem("0");
        idKMCB.setSelectedItem("0");
        idKHCB.setSelectedItem("0");
        clearText();
    }

    void clearText() {
        idSPCB.setSelectedItem("0");
        soLuongField.setText("");
        giaTienField.setText("");
        thanhTienField.setText("");
        tenSPField.setText("");
    }

    void addProduct() {
        int rowNumber = tableCTHD.getRowCount();
        int check = 0;
        for (int i = 0; i < rowNumber; i++) {
            if (tenSPField.getText().equals(tableCTHD.getValueAt(i, 0).toString())) {
                check++;
                break;
            }
        }
        if (check != 0) {
            JOptionPane.showMessageDialog(null, "Sản phẩm đã tồn tại trong hóa đơn !");
            clearText();
        } else {
            CthdDTO cthd = new CthdDTO(Integer.parseInt(idHDField.getText()), String.valueOf(idSPCB.getSelectedItem()), tenSPField.getText(), Integer.parseInt(soLuongField.getText()), Double.parseDouble(giaTienField.getText()), 1);
            bus.addCTHD(cthd);
            loadBill(idHDField.getText());
        }
    }

    public void thongBaoTontaiCTHD() {
        JOptionPane.showMessageDialog(null, "Sản phẩm đã tồn tại trong hóa đơn !");
        clearText();
    }

    public void loadBill(String id) {
        double tong = 0, thanhtien = 0;
        Vector header1 = new Vector();
        header1.add("Tên sản phẩm");
        header1.add("SL");
        header1.add("Đơn giá");
        header1.add("Thành tiền");
        model1 = new DefaultTableModel(header1, 0);
        ArrayList<CthdDTO> cthds = bus.getAllCTHD();
        for (CthdDTO cthd : cthds) {
            if (String.valueOf(cthd.getIdHoaDon()).equals(id)) {
                double tongSP = cthd.getGiaTien() * cthd.getSoLuong();
                tong += tongSP;
                String[] rowData1 = {cthd.getTenSanPham(), String.valueOf(cthd.getSoLuong()), String.valueOf(cthd.getGiaTien()), String.valueOf(tongSP)};
                model1.addRow(rowData1);
            }
        }
        tableCTHD.setModel(model1);
        tableCTHD.getColumnModel().getColumn(0).setPreferredWidth(150);
        tableCTHD.getColumnModel().getColumn(1).setPreferredWidth(30);
        tableCTHD.getColumnModel().getColumn(2).setPreferredWidth(60);
        tableCTHD.getColumnModel().getColumn(3).setPreferredWidth(60);
        // Tính tiền
        if (!id.equals("something")) {
            double km = 0;
            if(String.valueOf(idKMCB.getSelectedItem()).equals("0")) {
                km = 0;
            } else {
                ArrayList<PromotionDTO> pro = bus4.searchPromotionById(String.valueOf(idKMCB.getSelectedItem()));
                km = pro.get(0).getPhanTramGiamGia();
            }
            if (kMLabel.getText().equalsIgnoreCase("KM / Giảm giá : ")) {
                thanhtien = tong;
            } else {
                thanhtien = tong - (tong * (km / 100));
            }
            DecimalFormat df = new DecimalFormat("#,###");
            String soTienDaDinhDang = df.format(thanhtien);
            String soTienDaDinhDang1 = df.format(tong);
            tongLabel.setText("Tổng cộng : " + soTienDaDinhDang1 + "đ");
            tongHoaDonLabel.setText("Phải thanh toán : " + soTienDaDinhDang + "đ");
            tongTien = thanhtien;
        }

    }
//    
//    void getCurrentId() {
//        ArrayList<BillDTO> bills = bus2.getCurrentBillId();
//        for(BillDTO bill : bills) {
//            tongHoaDon = bill.getId();
//        }
//        if(tongHoaDon == 0) {
//            tongHoaDon = 2999; // trong DB bắt đầu từ 3000
//        }
//    }

//    void tinhtien() {
//        int rowNumber = tableCTHD.getRowCount();
//        for(int i = 0; i < rowNumber; i++) {
////            String value = tableCTHD.getValueAt(i, 3).toString().trim();
////            value = value.replace(',', '.'); // Thay thế dấu phẩy bằng dấu chấm nếu cần
//            tong =+ Double.parseDouble(tableCTHD.getValueAt(i, 3).toString());
//        }
//        tongLabel.setText("Tổng cộng : " + String.valueOf(tong));
//        thanhtien = tong - (tong * 0.2);
//        tongHoaDonLabel.setText("Phải thanh toán : " + String.valueOf(thanhtien));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton createBillBtn;
    private javax.swing.JButton deleteBtn;
    public javax.swing.JLabel demCTHD;
    public javax.swing.JLabel demCTHD1;
    public javax.swing.JTextField giaTienField;
    private javax.swing.JLabel giaTienLabel;
    public javax.swing.JTextField idHDField;
    public javax.swing.JComboBox<String> idKHCB;
    public javax.swing.JLabel idKHLabel;
    public javax.swing.JComboBox<String> idKMCB;
    public javax.swing.JLabel idLabel;
    public javax.swing.JTextField idNVField;
    public javax.swing.JLabel idNVLabel;
    public javax.swing.JComboBox<String> idSPCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel kMLabel;
    public javax.swing.JTextField soLuongField;
    private javax.swing.JTable tableCTHD;
    public javax.swing.JTextField tenSPField;
    private javax.swing.JLabel tenSPLabel;
    private javax.swing.JLabel tgLabel;
    public javax.swing.JTextField thanhTienField;
    private javax.swing.JLabel thanhTienLabel;
    public javax.swing.JLabel tongHoaDonLabel;
    public javax.swing.JLabel tongLabel;
    private javax.swing.JButton xuatHDBtn;
    // End of variables declaration//GEN-END:variables
}
