/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
/**
 *
 * @author Admin
 */
public class MenuPage extends javax.swing.JPanel {
    HomePage homepage;
    /**
     * Creates new form MenuPage
     */
    public MenuPage(HomePage homepage) {
        initComponents();
        this.homepage = homepage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        displayMenuPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BanhangBtn = new javax.swing.JButton();
        SanphamBt = new javax.swing.JButton();
        KhachhangBt = new javax.swing.JButton();
        ThongkeBtn = new javax.swing.JButton();
        NhanvienBt = new javax.swing.JButton();
        HoadonBt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        displayMenuPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        BanhangBtn1 = new javax.swing.JButton();
        SanphamBt1 = new javax.swing.JButton();
        KhachhangBt1 = new javax.swing.JButton();
        ThongkeBtn1 = new javax.swing.JButton();
        NhanvienBt1 = new javax.swing.JButton();
        HoadonBt1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(1125, 720));
        setPreferredSize(new java.awt.Dimension(1125, 720));

        displayMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayMenuPanel.setPreferredSize(new java.awt.Dimension(1125, 720));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        BanhangBtn.setBackground(new java.awt.Color(102, 102, 255));
        BanhangBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BanhangBtn.setForeground(new java.awt.Color(51, 51, 51));
        BanhangBtn.setText("Bán hàng");
        BanhangBtn.setToolTipText("");
        BanhangBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanhangBtn.setBorderPainted(false);
        BanhangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanhangBtn.setIconTextGap(5);
        BanhangBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setName(""); // NOI18N
        BanhangBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        BanhangBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BanhangBtnItemStateChanged(evt);
            }
        });
        BanhangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhangBtnActionPerformed(evt);
            }
        });

        SanphamBt.setBackground(new java.awt.Color(255, 0, 204));
        SanphamBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SanphamBt.setForeground(new java.awt.Color(51, 51, 51));
        SanphamBt.setText("Sản phẩm");
        SanphamBt.setToolTipText("");
        SanphamBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SanphamBt.setBorderPainted(false);
        SanphamBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamBt.setIconTextGap(5);
        SanphamBt.setMaximumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setMinimumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setName(""); // NOI18N
        SanphamBt.setPreferredSize(new java.awt.Dimension(63, 26));
        SanphamBt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SanphamBtItemStateChanged(evt);
            }
        });
        SanphamBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanphamBtActionPerformed(evt);
            }
        });

        KhachhangBt.setBackground(new java.awt.Color(51, 255, 255));
        KhachhangBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachhangBt.setText("Khách hàng");
        KhachhangBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt.setBorderPainted(false);
        KhachhangBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBtActionPerformed(evt);
            }
        });

        ThongkeBtn.setBackground(new java.awt.Color(153, 153, 153));
        ThongkeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongkeBtn.setText("Thống kê");
        ThongkeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongkeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongkeBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongkeBtnActionPerformed(evt);
            }
        });

        NhanvienBt.setBackground(new java.awt.Color(255, 51, 0));
        NhanvienBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NhanvienBt.setText("Nhân viên");
        NhanvienBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NhanvienBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanvienBt.setMaximumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setMinimumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setPreferredSize(new java.awt.Dimension(63, 26));
        NhanvienBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanvienBtActionPerformed(evt);
            }
        });

        HoadonBt.setBackground(new java.awt.Color(102, 102, 255));
        HoadonBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoadonBt.setText("Hóa đơn");
        HoadonBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HoadonBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoadonBt.setMaximumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setMinimumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setPreferredSize(new java.awt.Dimension(63, 26));
        HoadonBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(NhanvienBt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KhachhangBt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThongkeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(BanhangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoadonBt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SanphamBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BanhangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoadonBt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanphamBt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KhachhangBt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongkeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NhanvienBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayMenuPanelLayout = new javax.swing.GroupLayout(displayMenuPanel);
        displayMenuPanel.setLayout(displayMenuPanelLayout);
        displayMenuPanelLayout.setHorizontalGroup(
            displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanelLayout.createSequentialGroup()
                .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMenuPanelLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(displayMenuPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayMenuPanelLayout.setVerticalGroup(
            displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMenuPanelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(displayMenuPanelLayout.createSequentialGroup()
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(displayMenuPanelLayout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(displayMenuPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        displayMenuPanel1.setBackground(new java.awt.Color(255, 255, 255));
        displayMenuPanel1.setPreferredSize(new java.awt.Dimension(1125, 720));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        BanhangBtn1.setBackground(new java.awt.Color(102, 102, 255));
        BanhangBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BanhangBtn1.setForeground(new java.awt.Color(51, 51, 51));
        BanhangBtn1.setText("Bán hàng");
        BanhangBtn1.setToolTipText("");
        BanhangBtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanhangBtn1.setBorderPainted(false);
        BanhangBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanhangBtn1.setIconTextGap(5);
        BanhangBtn1.setMaximumSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.setMinimumSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.setName(""); // NOI18N
        BanhangBtn1.setPreferredSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BanhangBtn1ItemStateChanged(evt);
            }
        });
        BanhangBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhangBtn1ActionPerformed(evt);
            }
        });

        SanphamBt1.setBackground(new java.awt.Color(255, 0, 204));
        SanphamBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SanphamBt1.setForeground(new java.awt.Color(51, 51, 51));
        SanphamBt1.setText("Sản phẩm");
        SanphamBt1.setToolTipText("");
        SanphamBt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SanphamBt1.setBorderPainted(false);
        SanphamBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamBt1.setIconTextGap(5);
        SanphamBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        SanphamBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        SanphamBt1.setName(""); // NOI18N
        SanphamBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        SanphamBt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SanphamBt1ItemStateChanged(evt);
            }
        });
        SanphamBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanphamBt1ActionPerformed(evt);
            }
        });

        KhachhangBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachhangBt1.setText("Khách hàng");
        KhachhangBt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt1.setBorderPainted(false);
        KhachhangBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBt1ActionPerformed(evt);
            }
        });

        ThongkeBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongkeBtn1.setText("Thống kê");
        ThongkeBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongkeBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongkeBtn1.setMaximumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.setMinimumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.setPreferredSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongkeBtn1ActionPerformed(evt);
            }
        });

        NhanvienBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NhanvienBt1.setText("Nhân viên");
        NhanvienBt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NhanvienBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanvienBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanvienBt1ActionPerformed(evt);
            }
        });

        HoadonBt1.setBackground(new java.awt.Color(102, 102, 255));
        HoadonBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoadonBt1.setText("Hóa đơn");
        HoadonBt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HoadonBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoadonBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        HoadonBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        HoadonBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        HoadonBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonBt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(BanhangBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HoadonBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SanphamBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(NhanvienBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThongkeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KhachhangBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BanhangBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoadonBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanphamBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ThongkeBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KhachhangBt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(NhanvienBt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayMenuPanel1Layout = new javax.swing.GroupLayout(displayMenuPanel1);
        displayMenuPanel1.setLayout(displayMenuPanel1Layout);
        displayMenuPanel1Layout.setHorizontalGroup(
            displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayMenuPanel1Layout.setVerticalGroup(
            displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(displayMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BanhangBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BanhangBtnItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BanhangBtnItemStateChanged

    private void BanhangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanhangBtnActionPerformed
        // TODO add your handling code h
        homepage.addSalesPage();
    }//GEN-LAST:event_BanhangBtnActionPerformed

    private void SanphamBtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SanphamBtItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SanphamBtItemStateChanged

    private void SanphamBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanphamBtActionPerformed
        // TODO add your handling code here:
        homepage.addProdPage();
    }//GEN-LAST:event_SanphamBtActionPerformed

    private void KhachhangBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachhangBtActionPerformed
        // TODO add your handling code here:
        homepage.addCustPage();
    }//GEN-LAST:event_KhachhangBtActionPerformed

    private void ThongkeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongkeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThongkeBtnActionPerformed

    private void NhanvienBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanvienBtActionPerformed
        // TODO add your handling code here:
        homepage.addEmployPage();
    }//GEN-LAST:event_NhanvienBtActionPerformed

    private void HoadonBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoadonBtActionPerformed
        // TODO add your handling code here:
        homepage.addBillPage();
    }//GEN-LAST:event_HoadonBtActionPerformed

    private void BanhangBtn1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BanhangBtn1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BanhangBtn1ItemStateChanged

    private void BanhangBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanhangBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BanhangBtn1ActionPerformed

    private void SanphamBt1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SanphamBt1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SanphamBt1ItemStateChanged

    private void SanphamBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanphamBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SanphamBt1ActionPerformed

    private void KhachhangBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachhangBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KhachhangBt1ActionPerformed

    private void ThongkeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongkeBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThongkeBtn1ActionPerformed

    private void NhanvienBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanvienBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhanvienBt1ActionPerformed

    private void HoadonBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoadonBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoadonBt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanhangBtn;
    private javax.swing.JButton BanhangBtn1;
    private javax.swing.JButton HoadonBt;
    private javax.swing.JButton HoadonBt1;
    private javax.swing.JButton KhachhangBt;
    private javax.swing.JButton KhachhangBt1;
    private javax.swing.JButton NhanvienBt;
    private javax.swing.JButton NhanvienBt1;
    private javax.swing.JButton SanphamBt;
    private javax.swing.JButton SanphamBt1;
    private javax.swing.JButton ThongkeBtn;
    private javax.swing.JButton ThongkeBtn1;
    private javax.swing.JPanel displayMenuPanel;
    private javax.swing.JPanel displayMenuPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
