/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
/**
 *
 * @author Admin
 */
public class MenuPage extends javax.swing.JPanel {
    HomePage homepage;
    /**
     * Creates new form MenuPage
     */
    public MenuPage(HomePage homepage) {
        initComponents();
        this.homepage = homepage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        displayMenuPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BanhangBtn = new javax.swing.JButton();
        SanphamBt = new javax.swing.JButton();
        KhachhangBt = new javax.swing.JButton();
        ThongkeBtn = new javax.swing.JButton();
        NhanvienBt = new javax.swing.JButton();
        HoadonBt = new javax.swing.JButton();
        KhachhangBt2 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        displayMenuPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        BanhangBtn1 = new javax.swing.JButton();
        SanphamBt1 = new javax.swing.JButton();
        KhachhangBt1 = new javax.swing.JButton();
        ThongkeBtn1 = new javax.swing.JButton();
        NhanvienBt1 = new javax.swing.JButton();
        HoadonBt1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(1125, 720));
        setPreferredSize(new java.awt.Dimension(1125, 720));

        displayMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayMenuPanel.setPreferredSize(new java.awt.Dimension(1125, 720));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        BanhangBtn.setBackground(new java.awt.Color(0, 0, 0));
        BanhangBtn.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        BanhangBtn.setForeground(new java.awt.Color(255, 255, 102));
        BanhangBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-shopping-cart-40.png")); // NOI18N
        BanhangBtn.setText("   Bán hàng");
        BanhangBtn.setToolTipText("");
        BanhangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanhangBtn.setIconTextGap(5);
        BanhangBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setName(""); // NOI18N
        BanhangBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        BanhangBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BanhangBtnItemStateChanged(evt);
            }
        });
        BanhangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhangBtnActionPerformed(evt);
            }
        });

        SanphamBt.setBackground(new java.awt.Color(204, 204, 255));
        SanphamBt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SanphamBt.setForeground(new java.awt.Color(204, 102, 0));
        SanphamBt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-toy-40.png")); // NOI18N
        SanphamBt.setText("  Sản phẩm");
        SanphamBt.setToolTipText("");
        SanphamBt.setBorderPainted(false);
        SanphamBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamBt.setIconTextGap(5);
        SanphamBt.setMaximumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setMinimumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setName(""); // NOI18N
        SanphamBt.setPreferredSize(new java.awt.Dimension(63, 26));
        SanphamBt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SanphamBtItemStateChanged(evt);
            }
        });
        SanphamBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanphamBtActionPerformed(evt);
            }
        });

        KhachhangBt.setBackground(new java.awt.Color(204, 255, 204));
        KhachhangBt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KhachhangBt.setForeground(new java.awt.Color(255, 102, 102));
        KhachhangBt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-customer-40.png")); // NOI18N
        KhachhangBt.setText(" Khách hàng");
        KhachhangBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt.setBorderPainted(false);
        KhachhangBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBtActionPerformed(evt);
            }
        });

        ThongkeBtn.setBackground(new java.awt.Color(255, 255, 204));
        ThongkeBtn.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        ThongkeBtn.setForeground(new java.awt.Color(255, 51, 102));
        ThongkeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-chart-48.png")); // NOI18N
        ThongkeBtn.setText("  Thống kê");
        ThongkeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongkeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongkeBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongkeBtnActionPerformed(evt);
            }
        });

        NhanvienBt.setBackground(new java.awt.Color(153, 255, 255));
        NhanvienBt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NhanvienBt.setForeground(new java.awt.Color(0, 51, 51));
        NhanvienBt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-employee-40.png")); // NOI18N
        NhanvienBt.setText("  Nhân viên");
        NhanvienBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NhanvienBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanvienBt.setMaximumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setMinimumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setPreferredSize(new java.awt.Dimension(63, 26));
        NhanvienBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanvienBtActionPerformed(evt);
            }
        });

        HoadonBt.setBackground(new java.awt.Color(255, 153, 153));
        HoadonBt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HoadonBt.setForeground(new java.awt.Color(255, 255, 255));
        HoadonBt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\DoAnBanDoChoiTreEm\\mavenproject1\\src\\main\\java\\UI\\icons8-bill-40.png")); // NOI18N
        HoadonBt.setText(" Hóa đơn");
        HoadonBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoadonBt.setMaximumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setMinimumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setPreferredSize(new java.awt.Dimension(63, 26));
        HoadonBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonBtActionPerformed(evt);
            }
        });

        KhachhangBt2.setBackground(new java.awt.Color(204, 204, 204));
        KhachhangBt2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KhachhangBt2.setForeground(new java.awt.Color(102, 102, 102));
        KhachhangBt2.setText("Khuyến mãi");
        KhachhangBt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt2.setBorderPainted(false);
        KhachhangBt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt2.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt2.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt2.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BanhangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoadonBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(NhanvienBt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KhachhangBt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KhachhangBt2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThongkeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanphamBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoadonBt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanphamBt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanhangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NhanvienBt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhachhangBt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongkeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhachhangBt2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(242, 246, 242));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayMenuPanelLayout = new javax.swing.GroupLayout(displayMenuPanel);
        displayMenuPanel.setLayout(displayMenuPanelLayout);
        displayMenuPanelLayout.setHorizontalGroup(
            displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(displayMenuPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayMenuPanelLayout.setVerticalGroup(
            displayMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanelLayout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        displayMenuPanel1.setBackground(new java.awt.Color(255, 255, 255));
        displayMenuPanel1.setPreferredSize(new java.awt.Dimension(1125, 720));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        BanhangBtn1.setBackground(new java.awt.Color(102, 102, 255));
        BanhangBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BanhangBtn1.setForeground(new java.awt.Color(51, 51, 51));
        BanhangBtn1.setText("Bán hàng");
        BanhangBtn1.setToolTipText("");
        BanhangBtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanhangBtn1.setBorderPainted(false);
        BanhangBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanhangBtn1.setIconTextGap(5);
        BanhangBtn1.setMaximumSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.setMinimumSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.setName(""); // NOI18N
        BanhangBtn1.setPreferredSize(new java.awt.Dimension(63, 26));
        BanhangBtn1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BanhangBtn1ItemStateChanged(evt);
            }
        });
        BanhangBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhangBtn1ActionPerformed(evt);
            }
        });

        SanphamBt1.setBackground(new java.awt.Color(255, 0, 204));
        SanphamBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SanphamBt1.setForeground(new java.awt.Color(51, 51, 51));
        SanphamBt1.setText("Sản phẩm");
        SanphamBt1.setToolTipText("");
        SanphamBt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SanphamBt1.setBorderPainted(false);
        SanphamBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamBt1.setIconTextGap(5);
        SanphamBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        SanphamBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        SanphamBt1.setName(""); // NOI18N
        SanphamBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        SanphamBt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SanphamBt1ItemStateChanged(evt);
            }
        });
        SanphamBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanphamBt1ActionPerformed(evt);
            }
        });

        KhachhangBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachhangBt1.setText("Khách hàng");
        KhachhangBt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt1.setBorderPainted(false);
        KhachhangBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBt1ActionPerformed(evt);
            }
        });

        ThongkeBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongkeBtn1.setText("Thống kê");
        ThongkeBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongkeBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongkeBtn1.setMaximumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.setMinimumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.setPreferredSize(new java.awt.Dimension(63, 26));
        ThongkeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongkeBtn1ActionPerformed(evt);
            }
        });

        NhanvienBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NhanvienBt1.setText("Nhân viên");
        NhanvienBt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NhanvienBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanvienBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        NhanvienBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanvienBt1ActionPerformed(evt);
            }
        });

        HoadonBt1.setBackground(new java.awt.Color(102, 102, 255));
        HoadonBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoadonBt1.setText("Hóa đơn");
        HoadonBt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HoadonBt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoadonBt1.setMaximumSize(new java.awt.Dimension(63, 26));
        HoadonBt1.setMinimumSize(new java.awt.Dimension(63, 26));
        HoadonBt1.setPreferredSize(new java.awt.Dimension(63, 26));
        HoadonBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonBt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(BanhangBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HoadonBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SanphamBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(NhanvienBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThongkeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KhachhangBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BanhangBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoadonBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanphamBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ThongkeBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KhachhangBt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(NhanvienBt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayMenuPanel1Layout = new javax.swing.GroupLayout(displayMenuPanel1);
        displayMenuPanel1.setLayout(displayMenuPanel1Layout);
        displayMenuPanel1Layout.setHorizontalGroup(
            displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayMenuPanel1Layout.setVerticalGroup(
            displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(displayMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayMenuPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(displayMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    private void BanhangBtnItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void BanhangBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code h
        homepage.addSalesPage();
    }                                          

    private void SanphamBtItemStateChanged(java.awt.event.ItemEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SanphamBtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        homepage.addProdPage();
    }                                         

    private void KhachhangBtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        homepage.addCustPage();
    }                                           

    private void ThongkeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        homepage.addStatisticalPage();
    }                                          

    private void NhanvienBtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        homepage.addEmployPage();
    }                                          

    private void HoadonBtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        homepage.addBillPage();
    }                                        

    private void BanhangBtn1ItemStateChanged(java.awt.event.ItemEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void BanhangBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void SanphamBt1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void SanphamBt1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void KhachhangBt1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void ThongkeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        homepage.addStatisticalPage();
    }                                           

    private void NhanvienBt1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void HoadonBt1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void KhachhangBt2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        homepage.addPromotionPage();
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton BanhangBtn;
    private javax.swing.JButton BanhangBtn1;
    private javax.swing.JButton HoadonBt;
    private javax.swing.JButton HoadonBt1;
    private javax.swing.JButton KhachhangBt;
    private javax.swing.JButton KhachhangBt1;
    private javax.swing.JButton KhachhangBt2;
    private javax.swing.JButton NhanvienBt;
    private javax.swing.JButton NhanvienBt1;
    private javax.swing.JButton SanphamBt;
    private javax.swing.JButton SanphamBt1;
    private javax.swing.JButton ThongkeBtn;
    private javax.swing.JButton ThongkeBtn1;
    private javax.swing.JPanel displayMenuPanel;
    private javax.swing.JPanel displayMenuPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration                   
}
