/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Bill;

import java.awt.CardLayout;
import Bus.BillBUS;
import Bus.CthdBUS;
import Bus.PromotionBUS;
import UI.HomePage; // !!!!!!!!!!!!
import UI.Sales.SalesPage;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Inventory.DTO.BillDTO;
import Inventory.DTO.CthdDTO;
import Inventory.DTO.PromotionDTO;
import java.util.ArrayList;
import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Admin
 */
public class BillPage extends javax.swing.JPanel {
    DefaultTableModel model;
    DefaultTableModel model1; // dùng cho bảng CTHD
    BillBUS bus = new BillBUS();
    PromotionBUS bus4 = new PromotionBUS();
    int selectedRow = -1;
    HomePage homepage;
    SalesPage salespage;
    CthdBUS bus1 = new CthdBUS();
    /**
     * Creates new form BillPage
     */
    public BillPage(HomePage homepage, SalesPage salespage) {
        initComponents();
        this.homepage = homepage;
        this.salespage = salespage;
        loadAllBills();
        loadCTHD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        actionLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTHD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        displayActionPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        fromPriceSearchField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ngayXuatField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        idKHField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        toPriceSearchField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fromDaySearchField = new javax.swing.JTextField();
        toDaySearchField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        idNVField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tongTienField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        soCTHDField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kmField = new javax.swing.JTextField();
        timkiemBtn2 = new javax.swing.JButton();
        thenBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        timkiemBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        actionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        actionLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actionLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionLabel4.setText("Thông tin hóa đơn :");

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1125, 710));
        setPreferredSize(new java.awt.Dimension(1125, 710));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1075, 730));

        tableHoaDon.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tableHoaDon.setOpaque(false);
        tableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHoaDon);

        tableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCTHD);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết hóa đơn");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hóa đơn");

        actionPanel.setBackground(new java.awt.Color(238, 235, 235));

        displayActionPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayActionPanel.setMinimumSize(new java.awt.Dimension(600, 123));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 123));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Giá từ :");

        fromPriceSearchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Id nhân viên :");

        ngayXuatField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Id khách hàng:");

        idKHField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Id hóa đơn :");

        idField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Đến ngày :");

        toPriceSearchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Từ ngày :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Đến :");

        fromDaySearchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        toDaySearchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Số CTHD :");

        idNVField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Ngày xuất :");

        tongTienField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Tổng hóa đơn :");

        soCTHDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("_________________________________________________");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Id khuyến mãi :");

        kmField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kmField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fromDaySearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fromPriceSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idKHField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(idField)
                            .addComponent(tongTienField))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel14)))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDaySearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toPriceSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soCTHDField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNVField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idKHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idNVField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soCTHDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(ngayXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(kmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toPriceSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(fromPriceSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fromDaySearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(toDaySearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout displayActionPanelLayout = new javax.swing.GroupLayout(displayActionPanel);
        displayActionPanel.setLayout(displayActionPanelLayout);
        displayActionPanelLayout.setHorizontalGroup(
            displayActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayActionPanelLayout.setVerticalGroup(
            displayActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        timkiemBtn2.setBackground(new java.awt.Color(0, 0, 0));
        timkiemBtn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timkiemBtn2.setForeground(new java.awt.Color(255, 255, 255));
        timkiemBtn2.setText("Làm mới");
        timkiemBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemBtn2ActionPerformed(evt);
            }
        });

        thenBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thenBtn.setText("Thêm");
        thenBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thenBtnActionPerformed(evt);
            }
        });

        xoaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xoaBtn.setText("Xóa");
        xoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        timkiemBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timkiemBtn.setText("Tìm kiếm");
        timkiemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemBtnActionPerformed(evt);
            }
        });

        suaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suaBtn.setText("Chỉnh sửa");
        suaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });

        actionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionLabel.setText("Thông tin hóa đơn :");

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionLabel)
                    .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(actionPanelLayout.createSequentialGroup()
                            .addComponent(thenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(timkiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timkiemBtn2))
                        .addComponent(displayActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timkiemBtn2)
                    .addComponent(thenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xoaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timkiemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void tableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHoaDonMouseClicked
        // TODO add your handling code here:
       getSelectedRowInfo(); 
       loadCTHD();
    }//GEN-LAST:event_tableHoaDonMouseClicked

    private void timkiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemBtnActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        String idNV = idNVField.getText();
        String idKH = idKHField.getText();
        String soCTHD = soCTHDField.getText();
        String tongTien = tongTienField.getText();
        String ngayXuat = ngayXuatField.getText();
        String tuGia = fromPriceSearchField.getText();
        String denGia = toPriceSearchField.getText();
        String tuNgay = fromDaySearchField.getText();
        String denNgay = toDaySearchField.getText();
        String km = kmField.getText();
        Vector header = new Vector();
        header.add("ID");
        header.add("Id NV");
        header.add("Id KH");
        header.add("Số CTHD");
        header.add("Id KM");
        header.add("Tổng tiền");
        header.add("Ngày xuất");
        model = new DefaultTableModel(header, 0);
        ArrayList<BillDTO> bills = bus.getAllBills();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        long from = Long.MAX_VALUE;
        long to = Long.MIN_VALUE;
        if(tuGia.equals("") && !denGia.equals("") || !tuGia.equals("") && denGia.equals("") || tuNgay.equals("") && !denNgay.equals("") || !tuNgay.equals("") && denNgay.equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ thông tin tìm kiếm !");
        } else {
            if(!tuNgay.equals("") && !denNgay.equals("")) {
                try {
                    from = sdf.parse(tuNgay).getTime();
                    to = sdf.parse(denNgay).getTime();
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
            if(tuGia.equals("") && denGia.equals("")) {
                tuGia = "999999999999999999999999999999999999";
                denGia = "0";
            }
            for(BillDTO bill : bills) {
                long billDate = bill.getNgayXuat().getTime();
                if( String.valueOf(bill.getId()).equals(id) || bill.getIdNhanVien().equals(idNV) || bill.getIdKhachHang().equals(idKH) || String.valueOf(bill.getSoCTHD()).equalsIgnoreCase(soCTHD) || 
                    String.valueOf(bill.getIdKhuyenMai()).equals(km) || String.valueOf(bill.getTongTien()).equals(tongTien) || String.valueOf(bill.getNgayXuat()).equals(ngayXuat) ||
                   (billDate >= from && billDate <= to) || (bill.getTongTien() >= Double.parseDouble(tuGia) && bill.getTongTien( ) <= Double.parseDouble(denGia))) {
                        String[] rowData = {String.valueOf(bill.getId()), bill.getIdNhanVien(), bill.getIdKhachHang(), String.valueOf(bill.getSoCTHD()), String.valueOf(bill.getIdKhuyenMai()), String.valueOf(bill.getTongTien()), String.valueOf(bill.getNgayXuat())};
                        model.addRow(rowData);
                        System.out.println(bill.getId());
                }
            }
            tableHoaDon.setModel(model);
            tableHoaDon.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableHoaDon.getColumnModel().getColumn(1).setPreferredWidth(30);
            tableHoaDon.getColumnModel().getColumn(2).setPreferredWidth(30);
            tableHoaDon.getColumnModel().getColumn(3).setPreferredWidth(45);
            tableHoaDon.getColumnModel().getColumn(4).setPreferredWidth(30);
        }
        // tìm kiếm dưới DAO => bỏ
//        loadBillsByKeyword(id, idNV, idKH, soCTHD, tongTien, ngayXuat, tuGia, denGia, tuNgay, denNgay, km);
    }//GEN-LAST:event_timkiemBtnActionPerformed

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here:
        selectedRow = tableHoaDon.getSelectedRow();
        if(selectedRow != -1) {
            String removeId = tableHoaDon.getValueAt(selectedRow, 0).toString();
            bus.removeBill(Integer.parseInt(removeId));
            loadAllBills();
        } else {
            int removeId = Integer.parseInt(idField.getText());
            bus.removeBill(removeId);
            loadAllBills();
        }   
        clearTextField();
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void thenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thenBtnActionPerformed
        // TODO add your handling code here:
        if(actionLabel.getText().equalsIgnoreCase("Thông tin hóa đơn :")) {  
            homepage.addSalesPage();
        } else {
            
        }   
    }//GEN-LAST:event_thenBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed

        // truyen du lieu qa sale page de sua chua    
        if(!idField.getText().equals("")) {
            homepage.addSalesPage();
            salespage.idKHLabel.setText("Id khách hàng : " + idKHField.getText());
            salespage.idNVLabel.setText("Id nhân viên : " + idNVField.getText());
            salespage.idLabel.setText("Id hóa đơn : "+ idField.getText());
            salespage.tongLabel.setText("Tổng cộng : " + tongTienField.getText());
            salespage.idHDField.setEnabled(false);
            salespage.idHDField.setText(idField.getText());
            salespage.idNVField.setText(idNVField.getText());
            salespage.idKMCB.setSelectedItem(kmField.getText());
            salespage.idKHCB.setSelectedItem(idKHField.getText());
            ArrayList <PromotionDTO> pro = bus4.searchPromotionById(kmField.getText());
            salespage.kMLabel.setText("KM / Giảm giá : " + pro.get(0).getPhanTramGiamGia() + "%");
            salespage.loadBill(idField.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Hãy nhập id hóa đơn cần chỉnh sửa !");
        }
    }//GEN-LAST:event_suaBtnActionPerformed

    private void timkiemBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemBtn2ActionPerformed
        // TODO add your handling code here:
        clearTextField();
            // clear bang cthd
            model1.setRowCount(0);
            tableCTHD.setModel(model1);
            // load lai bang hoa don
            loadAllBills();
    }//GEN-LAST:event_timkiemBtn2ActionPerformed

    private void tableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCTHDMouseClicked
    
    private void getSelectedRowInfo(){
        selectedRow = tableHoaDon.getSelectedRow();
        if (selectedRow != -1) {
            idField.setText(tableHoaDon.getValueAt(selectedRow, 0).toString());
            idNVField.setText(tableHoaDon.getValueAt(selectedRow, 1).toString());
            idKHField.setText(tableHoaDon.getValueAt(selectedRow, 2).toString());
            soCTHDField.setText(tableHoaDon.getValueAt(selectedRow, 3).toString());
            tongTienField.setText(tableHoaDon.getValueAt(selectedRow, 5).toString());
            ngayXuatField.setText(tableHoaDon.getValueAt(selectedRow, 6).toString());
            kmField.setText(tableHoaDon.getValueAt(selectedRow, 4).toString());
        }
    }
    void clearTextField() {
            idField.setText("");
            idNVField.setText("");
            idKHField.setText("");
            soCTHDField.setText("");
            tongTienField.setText("");
            ngayXuatField.setText("");
            fromPriceSearchField.setText("");
            toPriceSearchField.setText("");
            fromDaySearchField.setText("");
            toDaySearchField.setText("");
            kmField.setText("");
    }
    
//    void getSelectedCTHDRowInfo() {
//        selectedCTHDRow = tableCTHD.getSelectedRow();
//        if (selectedCTHDRow != -1) {
//            cthd.demCTHD.setText("Chi tiết hóa đơn thứ : " + (selectedCTHDRow + 1));
//            cthd.idHoaDonField.setText(tableCTHD.getValueAt(selectedCTHDRow, 0).toString());
//            cthd.idSanPhamField.setText(tableCTHD.getValueAt(selectedCTHDRow, 1).toString());
//            cthd.tenSanPhamField.setText(tableCTHD.getValueAt(selectedCTHDRow, 2).toString());
//            cthd.soLuongField.setText(tableCTHD.getValueAt(selectedCTHDRow, 3).toString());
//            cthd.giaTienField.setText(tableCTHD.getValueAt(selectedCTHDRow, 4).toString());
//        }
//    }
    
    void loadAllBills() {
        Vector header = new Vector();
        header.add("ID");
        header.add("Id NV");
        header.add("Id KH");
        header.add("Số CTHD");
        header.add("Id KM");
        header.add("Tổng tiền");
        header.add("Ngày xuất");
        model = new DefaultTableModel(header, 0);
        ArrayList<BillDTO> bills = bus.getAllBills();
        for (BillDTO bill : bills) {
            String[] rowData = {String.valueOf(bill.getId()), bill.getIdNhanVien(), bill.getIdKhachHang(), String.valueOf(bill.getSoCTHD()), String.valueOf(bill.getIdKhuyenMai()), String.valueOf(bill.getTongTien()), String.valueOf(bill.getNgayXuat())};
            model.addRow(rowData);
        }
        tableHoaDon.setModel(model);
        tableHoaDon.getColumnModel().getColumn(0).setPreferredWidth(30);
        tableHoaDon.getColumnModel().getColumn(1).setPreferredWidth(30);
        tableHoaDon.getColumnModel().getColumn(2).setPreferredWidth(30);
        tableHoaDon.getColumnModel().getColumn(3).setPreferredWidth(45);
        tableHoaDon.getColumnModel().getColumn(4).setPreferredWidth(30);
    }
    
    void loadCTHD() {
        Vector header1 = new Vector();
        header1.add("Id hóa đơn");
        header1.add("Id sản phẩm");
        header1.add("Tên sản phẩm");
        header1.add("Số lượng");
        header1.add("Gía tiền mỗi SP");
        model1 = new DefaultTableModel(header1, 0);
        if(selectedRow != -1){
            String id = tableHoaDon.getValueAt(selectedRow, 0).toString();
            ArrayList<CthdDTO> cthds = bus1.getAllCTHD();
            for (CthdDTO cthd : cthds) {
                if(String.valueOf(cthd.getIdHoaDon()).equals(id)) {
                    String[] rowData1 = {String.valueOf(cthd.getIdHoaDon()), cthd.getIdSanPham(), cthd.getTenSanPham(), String.valueOf(cthd.getSoLuong()), String.valueOf(cthd.getGiaTien())};
                    model1.addRow(rowData1);
                }
            }
        }
        tableCTHD.setModel(model1); 
        tableCTHD.getColumnModel().getColumn(0).setPreferredWidth(30);
        tableCTHD.getColumnModel().getColumn(1).setPreferredWidth(30);
        tableCTHD.getColumnModel().getColumn(3).setPreferredWidth(30);
        tableCTHD.getColumnModel().getColumn(4).setPreferredWidth(50);
    }
    
//    void loadBillsByKeyword(String id, String idNV, String idKH, String soCTHD, String tongTien, String ngayXuat, String tuGia, String denGia, String tuNgay, String denNgay, String km) {
//        model.setRowCount(0);
//        ArrayList<BillDTO> bills = bus.getBillsByKeyword(id, idNV, idKH, soCTHD, tongTien, ngayXuat, tuGia, denGia, tuNgay, denNgay, km);
//        for (BillDTO bill : bills) {
//            String[] rowData = {String.valueOf(bill.getId()), bill.getIdNhanVien(), bill.getIdKhachHang(), String.valueOf(bill.getSoCTHD()), String.valueOf(bill.getTongTien()), String.valueOf(bill.getNgayXuat())};
//            model.addRow(rowData);
//        }
//        tableHoaDon.setModel(model);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel actionLabel4;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel displayActionPanel;
    public javax.swing.JTextField fromDaySearchField;
    public javax.swing.JTextField fromPriceSearchField;
    public javax.swing.JTextField idField;
    public javax.swing.JTextField idKHField;
    public javax.swing.JTextField idNVField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField kmField;
    public javax.swing.JTextField ngayXuatField;
    public javax.swing.JTextField soCTHDField;
    private javax.swing.JButton suaBtn;
    public javax.swing.JTable tableCTHD;
    public javax.swing.JTable tableHoaDon;
    private javax.swing.JButton thenBtn;
    private javax.swing.JButton timkiemBtn;
    private javax.swing.JButton timkiemBtn2;
    public javax.swing.JTextField toDaySearchField;
    public javax.swing.JTextField toPriceSearchField;
    public javax.swing.JTextField tongTienField;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
