/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo;
import Demo.LoginPage;
import Demo.Employee.EmployeePage;
import Demo.Customer.CustomerPage;
import Demo.Product.ProductPage;
import Demo.Bill.BillPage;
import Demo.Sales.SalesPage;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.*;

/**
 *
 * @author Admin
 */
public class HomePage extends javax.swing.JFrame {
    CardLayout layout;
    
    public HomePage(String userType) {
        initComponents();
        // set layout
        layout = new CardLayout();
        displayPanel.setLayout(layout);
        displayPanel.add("Sales", new SalesPage());
        displayPanel.add("Products", new ProductPage());
        displayPanel.add("Customers", new CustomerPage());
        displayPanel.add("Employees", new EmployeePage());
        displayPanel.add("Bills", new BillPage());
        // Them hoa don vao cardlayout
        if("EMPLOYEE".equalsIgnoreCase(userType)) {
            jPanel3.remove(NhanvienBt);
            jPanel3.remove(ThongkeBtn);
        }
//        getCurrentUser();
        setTitle("Quản lí bán đồ chơi trẻ em");
        setVisible(true);
    }
    public void addCustPage() {
        layout.show(displayPanel, "Customers");
    }
    public void addProdPage() {
        layout.show(displayPanel, "Products");
    }
    public void addEmployPage() {
        layout.show(displayPanel, "Employees");
    }
    public void addBillPage(){
        layout.show(displayPanel, "Bills");
    }
    public void addSalesPage() {
        layout.show(displayPanel, "Sales");
    }
    ///////////////
    private void getCurrentUser() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        HoadonBt = new javax.swing.JButton();
        NhanvienBt = new javax.swing.JButton();
        ThongkeBtn = new javax.swing.JButton();
        LogoutBt = new javax.swing.JButton();
        KhachhangBt = new javax.swing.JButton();
        SanphamBt = new javax.swing.JButton();
        BanhangBtn = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(160, 35));
        setMinimumSize(new java.awt.Dimension(1250, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(160, 692));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 560));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xin chao !");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 25));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        HoadonBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoadonBt.setText("Hóa đơn");
        HoadonBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HoadonBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoadonBt.setMaximumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setMinimumSize(new java.awt.Dimension(63, 26));
        HoadonBt.setPreferredSize(new java.awt.Dimension(63, 26));
        HoadonBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonBtActionPerformed(evt);
            }
        });

        NhanvienBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NhanvienBt.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Netbeans\\mavenproject1\\src\\main\\java\\Demo\\Employee\\Staff.png")); // NOI18N
        NhanvienBt.setText("Nhân viên");
        NhanvienBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NhanvienBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanvienBt.setMaximumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setMinimumSize(new java.awt.Dimension(63, 26));
        NhanvienBt.setPreferredSize(new java.awt.Dimension(63, 26));
        NhanvienBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanvienBtActionPerformed(evt);
            }
        });

        ThongkeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongkeBtn.setText("Thống kê");
        ThongkeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongkeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongkeBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        ThongkeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongkeBtnActionPerformed(evt);
            }
        });

        LogoutBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogoutBt.setText("Đăng xuất");
        LogoutBt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LogoutBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBt.setMaximumSize(new java.awt.Dimension(63, 26));
        LogoutBt.setMinimumSize(new java.awt.Dimension(63, 26));
        LogoutBt.setPreferredSize(new java.awt.Dimension(63, 26));
        LogoutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtActionPerformed(evt);
            }
        });

        KhachhangBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachhangBt.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Netbeans\\mavenproject1\\src\\main\\java\\Demo\\Customer\\Customer.png")); // NOI18N
        KhachhangBt.setText("Khách hàng");
        KhachhangBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachhangBt.setBorderPainted(false);
        KhachhangBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachhangBt.setMaximumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setMinimumSize(new java.awt.Dimension(63, 26));
        KhachhangBt.setPreferredSize(new java.awt.Dimension(63, 26));
        KhachhangBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachhangBtActionPerformed(evt);
            }
        });

        SanphamBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SanphamBt.setForeground(new java.awt.Color(51, 51, 51));
        SanphamBt.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Netbeans\\mavenproject1\\src\\main\\java\\Demo\\Product\\Product.png")); // NOI18N
        SanphamBt.setText("Sản phẩm");
        SanphamBt.setToolTipText("");
        SanphamBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SanphamBt.setBorderPainted(false);
        SanphamBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamBt.setIconTextGap(5);
        SanphamBt.setMaximumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setMinimumSize(new java.awt.Dimension(63, 26));
        SanphamBt.setName(""); // NOI18N
        SanphamBt.setPreferredSize(new java.awt.Dimension(63, 26));
        SanphamBt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SanphamBtItemStateChanged(evt);
            }
        });
        SanphamBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanphamBtActionPerformed(evt);
            }
        });

        BanhangBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BanhangBtn.setForeground(new java.awt.Color(51, 51, 51));
        BanhangBtn.setText("Bán hàng");
        BanhangBtn.setToolTipText("");
        BanhangBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanhangBtn.setBorderPainted(false);
        BanhangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanhangBtn.setIconTextGap(5);
        BanhangBtn.setMaximumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setMinimumSize(new java.awt.Dimension(63, 26));
        BanhangBtn.setName(""); // NOI18N
        BanhangBtn.setPreferredSize(new java.awt.Dimension(63, 26));
        BanhangBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BanhangBtnItemStateChanged(evt);
            }
        });
        BanhangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhangBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThongkeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HoadonBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NhanvienBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KhachhangBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SanphamBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BanhangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BanhangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(SanphamBt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(KhachhangBt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(NhanvienBt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(HoadonBt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ThongkeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LogoutBt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        displayPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayPanel.setMinimumSize(new java.awt.Dimension(1075, 700));
        displayPanel.setPreferredSize(new java.awt.Dimension(1075, 700));
        displayPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KhachhangBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachhangBtActionPerformed
        // TODO add your handling code here:
        addCustPage();
    }//GEN-LAST:event_KhachhangBtActionPerformed

    private void HoadonBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoadonBtActionPerformed
        // TODO add your handling code here:
        addBillPage();
    }//GEN-LAST:event_HoadonBtActionPerformed

    private void LogoutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage loginPage = new LoginPage();
    }//GEN-LAST:event_LogoutBtActionPerformed

    private void SanphamBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanphamBtActionPerformed
        // TODO add your handling code here:
        addProdPage();
    }//GEN-LAST:event_SanphamBtActionPerformed

    private void ThongkeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongkeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThongkeBtnActionPerformed

    private void NhanvienBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanvienBtActionPerformed
        // TODO add your handling code here:
        addEmployPage();
    }//GEN-LAST:event_NhanvienBtActionPerformed

    private void SanphamBtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SanphamBtItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SanphamBtItemStateChanged

    private void BanhangBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BanhangBtnItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BanhangBtnItemStateChanged

    private void BanhangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanhangBtnActionPerformed
        // TODO add your handling code h
        addSalesPage();
    }//GEN-LAST:event_BanhangBtnActionPerformed

 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanhangBtn;
    private javax.swing.JButton HoadonBt;
    private javax.swing.JButton KhachhangBt;
    private javax.swing.JButton LogoutBt;
    private javax.swing.JButton NhanvienBt;
    private javax.swing.JButton SanphamBt;
    private javax.swing.JButton ThongkeBtn;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
