/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Product;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class ProductPage extends javax.swing.JPanel {
    CardLayout layout;
    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        initComponents();
        layout = new CardLayout();
        displayActionPanel.setLayout(layout);
//        displayActionPanel.add("Add", new addCard());        
//        displayActionPanel.add("Remove", new removeCard());
    }
    private void addAction() {
       layout.show(displayActionPanel, "Add");
    }
    private void removeAction() {
       layout.show(displayActionPanel, "Remove");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        themBtn = new javax.swing.JButton();
        displayActionPanel = new javax.swing.JPanel();
        xoaBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        timkiemBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1075, 700));
        setPreferredSize(new java.awt.Dimension(1075, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sản phẩm");

        actionPanel.setBackground(new java.awt.Color(246, 243, 243));

        themBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themBtn.setForeground(new java.awt.Color(51, 51, 51));
        themBtn.setText("Thêm");
        themBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        themBtn.setBorderPainted(false);
        themBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        displayActionPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayActionPanel.setLayout(new java.awt.CardLayout());

        xoaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xoaBtn.setForeground(new java.awt.Color(51, 51, 51));
        xoaBtn.setText("Xóa");
        xoaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        xoaBtn.setBorderPainted(false);
        xoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        suaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaBtn.setForeground(new java.awt.Color(51, 51, 51));
        suaBtn.setText("Sửa");
        suaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suaBtn.setBorderPainted(false);
        suaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });

        timkiemBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timkiemBtn.setForeground(new java.awt.Color(51, 51, 51));
        timkiemBtn.setText("Tìm kiếm");
        timkiemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timkiemBtn.setBorderPainted(false);
        timkiemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(displayActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(timkiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
          addAction();
//        // TODO add your handling code here:
//        String ten = tenSP.getText();
//        String gia = giaSP.getText();
//        String xuatxu = xuatxuSP.getText();
//        String soluong = soluongSP.getText();
//        String Status = "true";
//        if(ten == null || gia == null || xuatxu == null || soluong == null ) {
//            JOptionPane.showMessageDialog(null, "Hãy điền đủ thông tin !");
//            tenSP.setText("");
//            giaSP.setText("");
//            xuatxuSP.setText("");
//            soluongSP.setText("");
//        } else {
//            try {
//                Connection con = Database.ConnectionProvider.getCon();
//                String query = "INSERT INTO SanPham (Ten,Xuatxu,Giatien,Soluongconlai,Status) VALUES (?, ?, ?, ?, ?)";
//                PreparedStatement ps = con.prepareStatement(query);
//                ps.setString(1, ten);
//                ps.setString(2, xuatxu);
//                ps.setString(3, gia);
//                ps.setString(4, soluong);
//                ps.setString(5, Status);
//
//                int rowsAffected = ps.executeUpdate();
//                if (rowsAffected > 0) {
//                    System.out.println("Dữ liệu đã được chèn thành công.");
//                } else {
//                    System.out.println("Không thể chèn dữ liệu.");
//                }
//
//                ps.close();
//                con.close();
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
//        }
        
    }//GEN-LAST:event_themBtnActionPerformed

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here:
        removeAction();
        
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suaBtnActionPerformed

    private void timkiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel displayActionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton suaBtn;
    private javax.swing.JButton themBtn;
    private javax.swing.JButton timkiemBtn;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
